image:
   file: Dockerfile
tasks:
  - command: 
      sbt new scala/scala3.g8
#      echo ROCKET_ADDRESS=$ROCKET_ADDRESS >> .env &&
#      echo ROCKET_PORT=$ROCKET_PORT >> .env &&
#      pg_start.sh &&
#      diesel setup &&
#      cargo build &&
#      cargo run
#ports:
# - port: 8000
vscode:
  extensions:
    - lampepfl.dotty@0.1.16:d3587c837b126b21148f85a481dfc3b8